
# needs to be on minerva
leafcutterPath: '/Users/jack/Software/leafcutter'


# now deprecated
#ipython2Path: '/usr/bin/python'
#python3Path: '/Users/jack/miniconda3/bin/python3'
python3Path: 'python3'

dataCode: 'TDP_example'

samples: 'samples.tsv'

ref: 'ref/gencode_hg38.gtf'

inFolder: 'data/'

outFolder: 'leafcutter/'

refCondition: 'control'
altCondition: 'tdp_kd'

#refFolder: "/Users/jack/Software/GENCODE/"
refFolder: "/hpc/users/humphj04/GENCODE/"
refFile: "gencode.v29.annotation.gtf.gz"
refCode: "gencode_hg38_v29"
# for regtools
# (0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR)
stranded: 2

