#####################
#Leafcutter Pipeline#
#####################


dataCode: 'kcnq2_run1'

metadata: 'samples.tsv'

# dataCode will be appended to outFolder
outFolder: 'results/'

# differential splicing - set reference and alternate conditions
refCondition: 'control'
altCondition: 'tdp_kd'

inFolder: 'data/'

# bamSuffix - what to append to the sample name to get the BAM file name
bamSuffix: '.bam'

# how the stranding was done (0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR)
# this assumes stranding same for every sample
stranded: 0


## Leafcutter settings ---------------------------------

leafcutterPath: '/hpc/users/humphj04/software/leafcutter'

leafcutter:
        # clustering options
        minCluRatio: 0.01
        minCluReads: 50
        intronMax: 100000
        n_threads: 4
        # ds options
        samplesPerIntron: 2
        samplesPerGroup: 2
        minCoverage: 20
        n_threads: 4
python3Path: 'python3'

refFolder: "/sc/orga/projects/ad-omics/data/references/hg38_reference/GENCODE/"
refFile: "gencode.v30.annotation.gtf.gz"
refCode: "gencode_hg38_v30"

