#####################
#Leafcutter Pipeline#
#####################


dataCode: 'PD_min_covariates'

metadata: 'meta_pd_control_multi_covariates.txt'

# dataCode will be appended to outFolder
outFolder: 'results/'

# differential splicing - set reference and alternate conditions
refCondition: 'Control'
altCondition: 'PD'

inFolder: 'data/'

# bamSuffix - what to append to the sample name to get the BAM file name
bamSuffix: '_Aligned.Quality.Sorted.bam'

# how the stranding was done (0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR)
# this assumes stranding same for every sample
stranded: 2


## Leafcutter settings ---------------------------------

leafcutterPath: '/hpc/users/humphj04/software/leafcutter'

leafcutter:
        # clustering options
        minCluRatio: 0.01
        minCluReads: 50
        intronMax: 100000
        # ds options
        samplesPerIntron: 5
        samplesPerGroup: 5
        minCoverage: 20

python3Path: 'python3'

refFolder: "/hpc/users/humphj04/GENCODE/"
refFile: "gencode.v30lift37.annotation.gtf.gz"
refCode: "gencode_hg19_v30"
